// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIjGxv5GMtOYbNcx3BtVRbaIkj6s_TZoA',
    appId: '1:198919449509:web:38c68a7deef8c42e47d64c',
    messagingSenderId: '198919449509',
    projectId: 'starterarchitectureflutterfb',
    authDomain: 'starterarchitectureflutterfb.firebaseapp.com',
    storageBucket: 'starterarchitectureflutterfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVuOI9yUFGUAWwU_AHgkDLqnHiUFC8tjk',
    appId: '1:198919449509:android:e5f8ad060530bf4e47d64c',
    messagingSenderId: '198919449509',
    projectId: 'starterarchitectureflutterfb',
    storageBucket: 'starterarchitectureflutterfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN2KmKKn5EMY5n0It50TYRZWip7kJsLPg',
    appId: '1:198919449509:ios:ae09d9c716f1974a47d64c',
    messagingSenderId: '198919449509',
    projectId: 'starterarchitectureflutterfb',
    storageBucket: 'starterarchitectureflutterfb.appspot.com',
    androidClientId: '198919449509-avf85gc83od1nl7isgkbnfi24cingp5c.apps.googleusercontent.com',
    iosClientId: '198919449509-88deaql0qjh146cb4gqhuvu023kv74mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );
}
